@echo off
echo Switching to NATIVE version...
copy /Y public\index-native.html public\index.html
echo Syncing to Android...
npx cap sync android
echo Done! Opening Android Studio...
npx cap open android
pause